kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drone-server-mysql-db 
  annotations:
    volume.beta.kubernetes.io/storage-class: "neunn-nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
