apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-03-30T21:14:38Z
  name: drone-config
  namespace: default
data:

  ################################
  # Drone Server (master) Config #
  ################################

  server.debug.is.enabled: "true"

  # You'll probably want to leave this alone, but you can point to external
  # DB instances if you'd like: http://readme.drone.io/0.7/manage/database/
  server.database.driver: mysql 
  server.database.config: drone:drone@tcp(10.2.16.8:30008)/drone?parseTime=true

  server.is.open: "false"
  # CHANGEME: If you want to restrict access to a particular org, put the
  # name here.
  server.orgs.list: ""
  # CHANGEME: Add your GitHub/Bitbucket/Gogs/etc username here. This is a
  # comma-separated list of usernames who will have admin privs.
  server.admin.list: donghb,root
  server.admin.everyone.is.admin: "false"

  # See http://readme.drone.io/0.5/manage/server/ for possible values here.
  # For now, our demo is GitHub-only. Drone supports other remotes, we just
  # haven't set the others up in here yet.
  # CHANGEME: Substitute your Github OAuth application client ID and secret.
  server.remote.gitlab.is.enabled: "true"
  server.remote.gitlab.client.id: d1a8bd24377f181efa9b2c49b9749af5c5c54d35dba431a156443d7afbf32cb4
  server.remote.gitlab.secret: 69cd1c347bf3775ef9f5dac4f7ef6b0eeaa22cabf3aea5b94c8746cc471e836b
  server.remote.gitlab.url: http://10.2.18.9
  server.host.path: http://10.2.16.8:30749

  ######################
  # Drone Agent Config #
  ######################

  agent.debug.is.enabled: "true"
