apiVersion: v1
kind: Service
metadata:
  name: drone-server
  labels:
    provider: drone-server
    heritage: drone-demos
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: http-new
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    name: drone-server
  type: NodePort
