apiVersion: v1
kind: ReplicationController
metadata:
  name: drone-server
  labels:
    heritage: drone-demos
spec:
  replicas: 1
  selector:
    name: drone-server
  template:
    metadata:
      labels:
        name: drone-server
    spec:
      containers:
        - image: drone/drone:0.8.1
          imagePullPolicy: IfNotPresent
          name: drone-server
          env:
            - name: DRONE_SERVER_ADDR
              value: ":80"
            - name: I_UNDERSTAND_I_AM_USING_AN_UNSTABLE_VERSION
              value: "true"
            - name: I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS
              value: "true"
            - name: DRONE_HOST
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: server.host.path
            - name: DRONE_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: server.debug.is.enabled
            - name: DRONE_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone-secrets
                  key: server.secret

            - name: DRONE_DATABASE_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: server.database.driver
            - name: DRONE_DATABASE_DATASOURCE
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: server.database.config

            - name: DRONE_OPEN
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: server.is.open
            - name: DRONE_ORGS
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: server.orgs.list
            - name: DRONE_ADMIN
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: server.admin.list
            - name: DRONE_ADMIN_ALL
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: server.admin.everyone.is.admin

            - name: DRONE_GITLAB
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: server.remote.gitlab.is.enabled
            - name: DRONE_GITLAB_CLIENT
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: server.remote.gitlab.client.id
            - name: DRONE_GITLAB_SECRET
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: server.remote.gitlab.secret
            - name: DRONE_GITLAB_URL
              valueFrom:
                configMapKeyRef:
                  name: drone-config
                  key: server.remote.gitlab.url
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            # Persist our configs in an SQLite DB in here
            - mountPath: /var/lib/drone
              name: drone-server-mysql-db
            # Enables Docker in Docker
            - mountPath: /var/run/docker.sock
              name: docker-socket
          resources:
            requests:
              cpu: 40m
              memory: 32Mi
      volumes:
        - name: drone-server-mysql-db
          persistentVolumeClaim:
            claimName: drone-server-mysql-db
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
