kind: Service
apiVersion: v1
metadata:
  labels:
    app: cicd-webdemo
  name: cicd-webdemo
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31438
  selector:
    app: cicd-webdemo
